name: Make epub

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: "--output=HowToMakeHerFlower.epub --metadata title=\"How to make her come\" introduction.md language.md fantasy.md notes.md afterword.md"

      - uses: actions/upload-artifact@master
        with:
          name: epub
          path: HowToMakeHerFlower.epub

