name: Make epub

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: m4 index.m4 > index.md
      - uses: docker://pandoc/core:2.9
        with:
          args: --output=HowToMakeHerFlower.epub index.md

      - uses: actions/upload-artifact@master
        with:
          name: epub
          path: HowToMakeHerFlower.epub

